name: roles_challenge
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
  build_runner: ^2.1.10
